### ISSUE TITLE
"True" "False" Randomly appears on screen while navigating

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/uno.todo#171]
## Current behavior

"True" "False" Randomly appears on screen while navigating

https://user-images.githubusercontent.com/29584087/165991161-c08f6485-3780-4261-996d-0c60884013e3.mov

## Expected behavior
No random text appearing in layouts

## How to reproduce it (as minimally and precisely as possible)

Click through lists and observe

## Environment

MacOS 
Chrome Version 100.0.4896.75 (Official Build) (x86_64) 
Private window
Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@nickrandolph / @dr1rrb Is this related to the FeedView or to something else related to Uno.Extensions?

**Comment by nickrandolph** [comment]
I think it's the FeedView but it maybe that this is being displayed before the correct viewmodel is set as the datacontext. @dr1rrb if you can take a look at the FeedView and let me know if you need me to investigate further
