### ISSUE TITLE
Custom Colours for "Important" and "Task" Lists aren't displayed and neither are their empty states

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/uno.todo#175]
## Current behavior

![image](https://user-images.githubusercontent.com/29584087/165993752-b7e7db88-1c5e-4b95-86a0-c45c9b86824e.png)
## Expected behavior

![image](https://user-images.githubusercontent.com/29584087/165993924-18d74d49-9485-4175-b58c-f700b422660c.png)

## How to reproduce it (as minimally and precisely as possible)

Go to Important List
Observe
## Environment

MacOS
Chrome Version 100.0.4896.75 (Official Build) (x86_64)
Private window
Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by agneszitte-nventive** [comment]
@NVLudwig custom color for the important task list is fixed in the PR I made https://github.com/unoplatform/uno.todo/pull/188

Issues left to be fixed:  loading / empty / error states
