### ISSUE TITLE
REFACTORING/CLEANUP: Removed unused VMs

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno.todo#219]

**Comment by agneszitte-nventive** [comment]
Any work left for this issue @Robert-Louis ? Blocker ?

**Comment by Robert-Louis** [comment]
forgot to closed it. All present vm are used for navigation when empty.

**Comment by agneszitte-nventive** [comment]
Closing the issue then, thanks for the feedback @Robert-Louis
