### ISSUE TITLE
BUG: Updating a task does not update the corresponding item in the list.

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno.todo#251]
1. Open the app in WASM
2. Open a task list with non-completed tasks
3. Open a task
4. Complete it by clicking the checkbox in the TaskDetail pane on the right
5. Observe the item stays "incompleted" in the list.
6. Switch to the "COMPLETED" list, and see a completed version of the task is there
7. Come back to the "TODO" list, and observe an incompleted version STILL there.

**Comment by agneszitte-nventive** [comment]
cc @nickrandolph
